"""Add category column to products

Revision ID: e5699365c8ef
Revises: c0f828767d02
Create Date: 2024-09-23 23:00:52.333193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5699365c8ef'
down_revision: Union[str, None] = 'c0f828767d02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'category')
    # ### end Alembic commands ###
